server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes[0]:
        id: formacion-server
        uri: lb://formacion-server
        predicates: Path=/api/formacion/**
        filters: StripPrefix=2
      routes[1]:
        id: maestro-server
        uri: lb://maestro-server
        predicates: Path=/api/maestro/**
        filters: StripPrefix=2